version: '2'
services:
  cog:
    environment:
      - COG_HIPCHAT_ENABLED=1
      - HIPCHAT_API_TOKEN=${HIPCHAT_API_TOKEN}
      - HIPCHAT_JABBER_ID=${HIPCHAT_JABBER_ID}
      - HIPCHAT_JABBER_PASSWORD=${HIPCHAT_JABBER_PASSWORD}
      - HIPCHAT_NICKNAME=${HIPCHAT_NICKNAME}
      - COG_BOOTSTRAP_USERNAME=admin
      - COG_BOOTSTRAP_PASSWORD=changeme
      - COG_BOOTSTRAP_EMAIL_ADDRESS=cog@localhost
      - COG_BOOTSTRAP_FIRST_NAME=Cog
      - COG_BOOTSTRAP_LAST_NAME=Administrator
      - RELAY_ID=00000000-0000-0000-0000-000000000000
      - RELAY_COG_TOKEN=supersecret

  relay:
    environment:
      - RELAY_ID=00000000-0000-0000-0000-000000000000
      - RELAY_COG_TOKEN=supersecret
